"""empty message

Revision ID: fe0f371f4474
Revises: 4aae72adbfd9
Create Date: 2023-01-24 19:30:03.601638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0f371f4474'
down_revision = '4aae72adbfd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currancy_rates', schema=None) as batch_op:
        batch_op.alter_column('id_curr',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currancy_rates', schema=None) as batch_op:
        batch_op.alter_column('id_curr',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
